enum Tier {
  HOBBY = 'HOBBY',
  ENTERPRISE = 'ENTERPRISE',
  FREE = 'FREE',
}
enum TaskQueueAction {
  IMAGE_UPLOAD = 'IMAGE_UPLOAD',
  IMAGE_PROCESSING_COMPLETED = 'IMAGE_PROCESSING_COMPLETED',
  IMAGE_PROCESSING_MANUAL_REVIEW = 'IMAGE_PROCESSING_MANUAL_REVIEW',
  INCREMENT_REDIRECT_STATS = 'INCREMENT_REDIRECT_STATS',
  ORDER_PLACED = 'ORDER_PLACED',
  INVENTORY_RESERVE_REQUESTED = 'INVENTORY_RESERVE_REQUESTED',
}
export { Tier, TaskQueueAction };
