enum Tier {
  HOBBY = 'HOBBY',
  ENTERPRISE = 'ENTERPRISE',
  FREE = 'FREE',
}
enum TaskQueueAction {
  GENERATE_THUMBNAIL = 'GENERATE_THUMBNAIL',
  INCREMENT_REDIRECT_STATS = 'INCREMENT_REDIRECT_STATS',
}
export { Tier, TaskQueueAction };
